version: '3'

services:
  web:
    build: .
    ports:
      - "4000:4000"
      - "4001:35729"
      - "6006:6006"
    restart: on-failure
    volumes:
      - .:/app
    environment:
      - API_URL=${API_URL-http://127.0.0.1:8000}
      - NODE_ENV=${NODE_ENV-development}
      - PORT=4000
