name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Eslint
        env:
          NPM_CONFIG_PREFIX: "~/.npm-global"
        run: |
          npm install
          npm install -g eslint
          bash -c "eslint src/ --ext=.js*
